apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
      - name: ai-service-container
        image: amithpalissery/ai-service:1.0.0
        ports:
        - containerPort: 5001
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-service-secrets
              key: GOOGLE_API_KEY
        - name: CHAT_HISTORY_SERVICE_URL
          value: http://chat-history-service:5002
