apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
      - name: ai-service-container
        image: amithpalissery/ai-service:1.0.1
        ports:
        - containerPort: 5001
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-service-secrets
              key: GOOGLE_API_KEY
        - name: CHAT_HISTORY_SERVICE_URL
          value: http://chat-history-service:5002
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
