apiVersion: v1
kind: Service
metadata:
  name: chat-history-service
spec:
  selector:
    app: chat-history-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
