apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-history-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-history-service
  template:
    metadata:
      labels:
        app: chat-history-service
    spec:
      containers:
      - name: chat-history-container
        image: amithpalissery/chat-history-service:1.0.1
        ports:
        - containerPort: 5002
        env:
        - name: DATABASE_PATH
          value: /app/chat_history.db
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
