name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push AI service image
        uses: docker/build-push-action@v5
        with:
          context: ./ai-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-service:${{ github.sha }}
          file: ./ai-service/Dockerfile

      - name: Build and push chat-history-service image
        uses: docker/build-push-action@v5
        with:
          context: ./chat-history-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-history-service:${{ github.sha }}
          file: ./chat-history-service/Dockerfile

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
          file: ./frontend/Dockerfile

  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create or update secrets for AI service
        run: |
          echo "
          apiVersion: v1
          kind: Secret
          metadata:
            name: ai-service-secrets
          type: Opaque
          stringData:
            GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          " | kubectl apply -f -

      - name: Deploy with Helm
        run: |
          helm upgrade --install chatbot-release ./chatbot-microservice-chart \
            --set frontend.image.tag=${{ github.sha }} \
            --set aiService.image.tag=${{ github.sha }} \
            --set chatHistoryService.image.tag=${{ github.sha }}
