name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify the version your frontend needs

      - name: Run frontend linter
        run: |
          cd frontend
          npm install
          npm run lint
      
      - name: Run frontend unit tests
        run: |
          cd frontend
          npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push AI service image
        uses: docker/build-push-action@v5
        with:
          context: ./ai-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-service:${{ github.sha }}
          file: ./ai-service/Dockerfile

      - name: Build and push chat-history-service image
        uses: docker/build-push-action@v5
        with:
          context: ./chat-history-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-history-service:${{ github.sha }}
          file: ./chat-history-service/Dockerfile

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
          file: ./frontend/Dockerfile

  security-scan:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Scan AI service image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/ai-service:${{ github.sha }}'
          severity: 'CRITICAL,HIGH'
          exit-code: '1' # This makes the job fail if critical/high vulnerabilities are found

      - name: Scan chat-history-service image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/chat-history-service:${{ github.sha }}'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: Scan frontend image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

  deploy:
    runs-on: self-hosted
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy with Helm
        run: |
          helm upgrade --install chatbot-release ./chatbot-microservice-chart \
            --set frontend.image.tag=${{ github.sha }} \
            --set aiService.image.tag=${{ github.sha }} \
            --set chatHistoryService.image.tag=${{ github.sha }}
