name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    outputs:
      tag: ${{ steps.set-tag.outputs.TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: set-tag
        run: echo "TAG=1.0.1-${{ github.run_number }}" >> $GITHUB_ENV
        
      - name: Build and push AI service image
        uses: docker/build-push-action@v5
        with:
          context: ./ai-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-service:${{ env.TAG }}
          file: ./ai-service/Dockerfile

      - name: Build and push chat-history-service image
        uses: docker/build-push-action@v5
        with:
          context: ./chat-history-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-history-service:${{ env.TAG }}
          file: ./chat-history-service/Dockerfile

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ env.TAG }}
          file: ./frontend/Dockerfile



  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy with Helm
        run: |
          helm upgrade --install chatbot-release ./chatbot-microservice-chart \
            --set frontend.image.tag=${{ needs.build-and-push.outputs.tag }} \
            --set aiService.image.tag=${{ needs.build-and-push.outputs.tag }} \
            --set chatHistoryService.image.tag=${{ needs.build-and-push.outputs.tag }}
